spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 38782F413F4428472B4B6250655368566D597133743677397924422645294840
      expiration: 86400000 #86400000 for one day.
      refresh-token:
        expiration: 604800000 #for 7 day.