<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap demo</title>
<style type="text/css">
	.error{
		color: red;
	}
</style>
<link
	href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
	rel="stylesheet"
	integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
	crossorigin="anonymous">
</head>
<body>

	<div class="m-5">
	
	<h3 class="text-center">Register Student</h3>
	<form:form action="save-student" method="post" modelAttribute="stud">
		<div class="mb-3">
			<form:label path="rollNo" class="form-label" >Roll No.</form:label>
			<form:input path="rollNo" class="form-control" disabled="true" aria-describedby="rollnoHelp" />
			<div id="rollnoHelp" class="form-text">It will be auto-generated by the System.</div>
		</div>
		
		<div class="mb-3">
			<form:label path="stuName" class="form-label" >Name</form:label>
			<form:input path="stuName" class="form-control" />
			<form:errors path="stuName" class="error" />
		</div>
		
		<div class="mb-3">
			<form:label path="stuEmail" class="form-label" >Email </form:label>
			<form:input path="stuEmail" class="form-control" />
			<form:errors path="stuEmail" class="error" />
		</div>
		
		<div class="mb-3">
			<form:label path="course" class="form-label" >Course </form:label>
			<form:input path="course" class="form-control" />
			<form:errors path="course" class="error" />
		</div>
		
		<input type="submit" value="Register" class="btn btn-primary"  />
	</form:form>
	
	</div>
	
	<script
		src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
		crossorigin="anonymous"></script>
</body>
</html>